# An API test using an end point

# 1- Importing key modules

In [1]:
import pickle
import re    # for regular expressions 
import nltk  # for text manipulation 
import string 
import numpy as np 
import pandas as pd 

#For Visuals
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from matplotlib import rcParams
rcParams['figure.figsize'] = 11, 8
%config InlineBackend.figure_format = 'svg'
%matplotlib inline

In [2]:
#models and evaluation

from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.naive_bayes import MultinomialNB
from nltk.classify.scikitlearn import SklearnClassifier # notice its from ntlk not sklearn
from sklearn.svm import LinearSVC, SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
# Evaluation packages
from sklearn.metrics import accuracy_score
from sklearn import metrics
from sklearn.metrics import confusion_matrix

# 2-Load Model & transformer CV

In [3]:
filename = 'finalized_model.sav'
loaded_model = pickle.load(open(filename, 'rb'))

In [4]:
filename2 = 'countvectorizer.sav'
cv = pickle.load(open(filename2, 'rb'))

# 3-Out of Sample data

In [5]:
message=["US jobs growth last month hit by weather:Fed President Charles Plosser"]

In [6]:
vect = pd.DataFrame(cv.transform(message).toarray())
my_prediction = loaded_model.predict(vect)
my_prediction

array([1], dtype=int64)

In [7]:
score=loaded_model.predict_proba(vect)
score

array([[0.98251183, 0.01369128, 0.00205359, 0.0017433 ]])

In [8]:
prob=score.max(axis=1)
prob

array([0.98251183])

In [9]:
result=message
result=pd.DataFrame(result,columns=["text"])
result["news-type"]=my_prediction
result["news-type"]=result['news-type'].map({1 : "b", 2 : "t", 3 :"e", 4:"m"})
result["probability"]=prob
result

text news-type  probability
0  US jobs growth last month hit by weather:Fed P...         b     0.982512

In [10]:
json_table = result.to_json(orient='records')  
json_table

'[{"text":"US jobs growth last month hit by weather:Fed President Charles Plosser","news-type":"b","probability":0.9825118325}]'

### 2nd example

In [13]:
message=["YouTube updates to include crowd-funding options"]
vect = pd.DataFrame(cv.transform(message).toarray())
my_prediction = loaded_model.predict(vect)
score=loaded_model.predict_proba(vect)
prob=score.max(axis=1)

In [14]:
result=message
result=pd.DataFrame(result,columns=["text"])
result["news-type"]=my_prediction
result["news-type"]=result['news-type'].map({1 : "b", 2 : "t", 3 :"e", 4:"m"})
result["probability"]=prob

In [16]:
result

text news-type  probability
0  YouTube updates to include crowd-funding options         t     0.628303

In [15]:
json_table = result.to_json(orient='records')  
json_table

'[{"text":"YouTube updates to include crowd-funding options","news-type":"t","probability":0.6283026096}]'